name: Super-linter

on: push

jobs:
	super-lint:
		name: lint code base
		runs-on: ubuntu-latest
		steps:
			- name: Checkout code
			  uses: actions/checkout@v2
			  
			- name: Run Super-linter
			  uses: github/super-linter@v3
			  env:
				Default Branc: main
				GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
